config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :employees
  resources :departments
  resources :bills, only: [:index, :new, :create]

  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee

  validates :bill_type, inclusion: { in: %w[food travel others], message: "%{value} is not a valid bill type" }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees

    validates :name, presence: true

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department

  has_many :bills

  validates :first_name, :last_name, :email, :designation, presence: true
  validates :email, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
    def index
        @bills = Bill.includes(:employee => :department).all

        @total_amount = @bills.sum(:amount)
    end
  
    def new
        @bill = Bill.new
        @employees = Employee.includes(:department).all
    end
  
    def create
        @bill = Bill.new(bill_params)
        if @bill.save
            redirect_to bills_path
        else
            @employees = Employee.includes(:department).all
            flash.now[:alert] = @bill.errors.full_messages.join(', ')
            render :new
        end
    end
  
    private
  
    def bill_params
        params.require(:bill).permit(:amount, :bill_type, :employee_id)
    end
end
  

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    before_action :set_department, only: [:show, :edit, :update, :destroy]
  
    def index
        @departments = Department.all
    end
  
    def show
    end
  
    def new
        @department = Department.new
    end
  
    def edit
    end
  
    def create
        @department = Department.new(department_params)
        if @department.save
            redirect_to departments_url, notice: 'Department was successfully created.'
        else
            render :new
        end
    end
  
    def update
        if @department.update(department_params)
            redirect_to departments_url, notice: 'Department was successfully updated.'
        else
            render :edit
        end
    end
  
    def destroy
        @department.employees.each do |employee|
            employee.bills.destroy_all
            employee.destroy
        end
        @department.destroy
        redirect_to departments_url, notice: 'Department was successfully destroyed.'
    end
  
    private
  
    def set_department
        @department = Department.find(params[:id])
    end
  
    def department_params
        params.require(:department).permit(:name)
    end
  end
  

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
    def index
        @employees = Employee.all
    end
  
    def show
    end
  
    def new
        @employee = Employee.new
    end
  
    def edit
    end
  
    def create
        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to employees_url, notice: 'Employee was successfully created.'
        else
            render :new
        end
    end
  
    def update
        if @employee.update(employee_params)
            redirect_to employees_url, notice: 'Employee was successfully updated.'
        else
            render :edit
        end
    end
  
    def destroy
        @employee.bills.destroy_all
        @employee.destroy
        redirect_to employees_url, notice: 'Employee was successfully destroyed.'
    end
  
    private
  
    def set_employee
        @employee = Employee.find(params[:id])
    end
  
    def employee_params
        params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/bills/index.html.erb
<%= render 'shared/navbar' %>
<div class= "container">
    <div class = "heading">
        <h1>Bills</h1>
        <%= link_to new_bill_path, class: 'btn btn-primary' do %>
            <i class="fas fa-plus"></i> New Bill
        <% end %>
    </div>
    <p>
        <h3>Total Submitted:<%= @total_amount %> </h3>
    </p>
    <table class="table">
        <thead>
            <tr class="table_heading table-secondary">
                <th>Type</th>
                <th>Amount</th>
                <th>Date of Submisson</th>
                <th>Submitted By</th>
                <th>Department</th>
            </tr>
        </thead>

        <tbody>
            <% @bills.each do |bill| %>
                <tr>
                    <td class = "t_data"><%= bill.bill_type %></td>
                    <td class = "t_data"><%= bill.amount %></td>
                    <td class = "t_data"><%= bill.created_at.strftime("%d-%m-%Y") %></td>
                    <td class = "t_data"><%= bill.employee.full_name %></td>
                    <td class = "t_data"><%= bill.employee.department.name %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/bills/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
    <h1>New Bill</h1>
    <div class="card">
        <div class="card-body">
            <%= form_for @bill, url: bills_path do |form| %>
                <div class="row mb-3">
                    <div class="col-lg-4">
                        <%= form.label :bill_type, class: 'form-label' %>
                        <%= form.select :bill_type, options_for_select([['Food', 'food'], ['Travel', 'travel'], ['Others', 'others']]), {include_blank: 'Choose...'}, class: 'form-select' %>
                    </div>

                    <div class="col col-lg-4">
                        <div class= "form-label">Amount</div>
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon-amount">&#8377</span>
                            <%= form.text_field :amount, class: 'form-control', placeholder: '', 'aria-label': 'Email', 'aria-describedby': 'basic-addon-email' %>
                        </div>
                    </div>


                    <div class="col-lg-4">
                        <%= form.label :employee_id, 'Submitted Employee', class: 'form-label' %>
                        <%= form.collection_select :employee_id, @employees, :id, :full_name, {include_blank: 'Select Employee'}, class: 'form-select' %>
                    </div>
                </div>
                <div class="bottom_buttons">
                    
                    <%= button_tag type: 'submit', class: 'btn btn-primary', data: { confirm: 'Are you sure?' } do %>
                        <i class="fa-solid fa-check"></i> Generate Bill
                    <% end %>

                    <%= link_to 'Back', bills_path %>
                        
                    
                </div>

            <% end %>
        </div>
    </div>
</div>

app/views/departments/_form.html.erb
<div class="container">
    <div class="card">
        <div class="card-body">
            <%= form_for(department) do |form| %>
                <% if department.errors.any? %>
                    <div id="error_explanation" class="alert alert-danger">
                        <h4 class="alert-heading"><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h4>
                        <ul>
                            <% department.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="mb-3">
                    <%= form.label :name, class: 'form-label' %>
                    <%= form.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="bottom_buttons">
                    <%= button_tag type: 'submit', class: 'btn btn-primary', data: { confirm: 'Are you sure?' } do %>
                        <i class="fa-solid fa-check"></i> Confirm
                    <% end %>

                    <%= link_to 'Back', departments_path %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/departments/edit.html.erb
 <%= render 'shared/navbar' %>
 <div class ="container"> 
    <h1>Update Department</h1>
</div>
<%= render 'form', department: @department %>

app/views/departments/index.html.erb
<%= render 'shared/navbar' %>
<div class= "container">
    <div class = "heading">
        <h1>Departments</h1>
        <%= link_to new_department_path, class: 'btn btn-primary' do %>
            <i class="fas fa-plus"></i> Create
        <% end %>
    </div>
    <table class="table">
        <thead>
            <tr class="table_heading table-secondary">
                <th>Name</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <% @departments.each do |department| %>
                <tr>
                    <td class = "t_data"><%= department.name %></td>

                    <td class = "t_data table_buttons">
                        <%= link_to edit_department_path(department), class: 'btn ' do %>
                            <i class="fa-solid fa-pen-to-square"></i> Edit
                        <% end %>

                        <%= link_to department, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
                            <i class="fas fa-trash"></i> Delete
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/departments/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
    <h1>New Department</h1>

    <%= render 'form', department: @department %>
</div>

app/views/departments/show.html.erb
<%= render 'shared/navbar' %>
<h1><%= @department.name %></h1>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/_form.html.erb
<%= form_for(employee, html: { class: 'form-horizontal' }) do |form| %>
    <% if employee.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

            <ul>
                <% employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class = "container">
        <div class="card">
            <div class="card-body">
                <div class = "row">
                    <div class="col col-lg-4">
                        <%= form.label :first_name, class: 'form-label' %>
                        <%= form.text_field :first_name, class: 'form-control' %>
                    </div>

                    <div class="col col-lg-4">
                        <%= form.label :last_name, class: 'form-label' %>
                        <%= form.text_field :last_name, class: 'form-control' %>
                    </div>

                    <div class="col col-lg-4">
                        <div class= "form-label">Email Address</div>
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon-email">@</span>
                            <%= form.email_field :email, class: 'form-control', placeholder: 'Email', 'aria-label': 'Email', 'aria-describedby': 'basic-addon-email' %>
                        </div>
                    </div>
                </div>


                <div class = "row">
                    <div class="col mb-3">
                        <%= form.label :designation, class: 'form-label' %>
                        <%= form.text_field :designation, class: 'form-control' %>
                    </div>

                    <div class="col mb-3">
                        <%= form.label :department_id, "Department", class: 'form-label' %>
                        <%= form.collection_select :department_id, Department.all, :id, :name,
                                                { include_blank: 'Choose...' }, 
                                                { class: 'form-select' } %>
                    </div>

                </div>

                <div class = "bottom_buttons">
                    <div class="actions">
                        <div class="mb-3">
                            <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
                                <i class="fa-solid fa-check"></i> Confirm
                            <% end %>
                        </div>
                    </div>
                    <%= link_to 'Back', employees_path %>
                </div>

            </div>
        </div>

    </div>

<% end %>

app/views/employees/edit.html.erb
 <%= render 'shared/navbar' %>
 <div class="container">
    <h1>Update Employee Details</h1>

    <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<%= render 'shared/navbar' %>

<div class= "container">
    <div class="heading">
        <h1>Employees</h1>
        <%= link_to new_employee_path, class: 'btn btn-primary' do %>
            <i class="fas fa-plus"></i> New Employee
        <% end %>

    </div>
    <table class="table">
        <thead>
            <tr class = "table_heading table-secondary">
                <th>Full Name</th>
                <th>Designation</th>
                <th>Department</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <% @employees.each do |employee| %>
                <tr>
                    <td class = "t_data"><%= employee.first_name %> <%= employee.last_name %></td>
                    <td class = "t_data"><%= employee.designation %></td>
                    <td class = "t_data"><%= employee.department.name %></td>
                    <td class = "t_data table_buttons">
                        <%= link_to employee, class: 'btn ' do %>
                            <i class="fa-solid fa-eye"></i>View
                        <% end %>

                        <%= link_to edit_employee_path(employee), class: 'btn' do %>
                            <i class="fa-solid fa-pen-to-square"></i>Edit
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/employees/new.html.erb
<%= render 'shared/navbar' %>
<div class= "container">    
    <h1>New Employee</h1>

    <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<%= render 'shared/navbar' %>


<div class= "container">
    <div class="card">
        <div class="card-body employee_show">
            <div class="row"> 
                <div class="col col-lg-6">
                    <p>
                        <h2 class="card-title"><%= @employee.first_name %> <%= @employee.last_name %></h2>
                    </p>
                    <p class="details">
                        <strong>Email:</strong>
                        <%= @employee.email %>
                    </p>

                    <p class="details">
                        <strong>Designation:</strong>
                        <%= @employee.designation %>
                    </p>

                    <p class="details">
                        <strong>Department:</strong>
                        <%= @employee.department.name %>
                    </p>
                </div>
                <div class="col col-lg-4">
                    <img src="https://picsum.photos/200" alt="Avatar" class="avatar">
                </div>
            </div>

            <div class = "bottom_buttons_show">
                <%= link_to 'Back', employees_path , class: 'btn btn-primary'%> 
                <%= link_to @employee, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="fas fa-trash"></i> Delete
                <% end %>
            </div>


        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeReimbursement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

        
    <div class="toast-container position-fixed top-0 end-0 p-3" style="z-index: 1050">
      <% flash.each do |key, message| %>
        <% if key == :toast %>
          <%= render 'shared/toast', notice: message %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Employees', employees_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bill', bills_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Department', departments_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>